#Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/book_ex?useUnicode=true&charaterEncoding=utf-8
spring:
  datasource:
    url: jdbc:mysql://tripper.cg08tx0ixoqm.ap-northeast-2.rds.amazonaws.com/book_ex?useUnicode=true&charaterEncoding=utf-8
    username: tripper
    password: trippersoma
    driverClassName: com.mysql.jdbc.Driver
#Jpa Option
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true


  servlet:
    multipart:
      max-file-size: 50000KB
      max-request-size: 50000KB
  mail:
    host: smtp.gmail.com
    port: 587
    username: llmooon1202
    password: hs466831by59
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
##MultiPart

amazonProperties:
  endpointUrl : https://s3.ap-northeast-2.amazonaws.com
  accessKey: AKIAIAXORZLZ2JSDFKOA
  secretKey: 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
  bucketName: tripper-bucket
  region : ap-northeast-2

